-- Escape Game Builder Supabase Storage buckets and policies.
-- Run this in the Supabase SQL editor, or adapt it for Supabase CLI migrations.
--
-- Bucket names are fixed SQL literals because Supabase SQL migrations cannot
-- read deployment environment variables. If your env vars use different names,
-- edit the two bucket-id functions below before running this file.

create or replace function public.escape_game_public_assets_bucket_id()
returns text
language sql
immutable
security invoker
set search_path = public
as $$
  select 'escape-game-public-assets'::text;
$$;

create or replace function public.escape_game_private_data_bucket_id()
returns text
language sql
immutable
security invoker
set search_path = public
as $$
  select 'escape-game-private-data'::text;
$$;

comment on function public.escape_game_public_assets_bucket_id()
is 'Escape Game Builder public Storage bucket id. Keep in sync with VITE_SUPABASE_PUBLIC_ASSETS_BUCKET and SUPABASE_PUBLIC_ASSETS_BUCKET.';

comment on function public.escape_game_private_data_bucket_id()
is 'Escape Game Builder private Storage bucket id. Keep in sync with VITE_SUPABASE_PRIVATE_DATA_BUCKET and SUPABASE_PRIVATE_DATA_BUCKET.';

revoke all on function public.escape_game_public_assets_bucket_id() from public;
revoke all on function public.escape_game_private_data_bucket_id() from public;
grant execute on function public.escape_game_public_assets_bucket_id() to anon, authenticated, service_role;
grant execute on function public.escape_game_private_data_bucket_id() to authenticated, service_role;

do $$
declare
  public_bucket_id constant text := public.escape_game_public_assets_bucket_id();
  private_bucket_id constant text := public.escape_game_private_data_bucket_id();
begin
  insert into storage.buckets (id, name, public)
  values
    (public_bucket_id, public_bucket_id, true),
    (private_bucket_id, private_bucket_id, false)
  on conflict (id) do update
  set
    name = excluded.name,
    public = excluded.public;
end $$;

alter table storage.objects enable row level security;

create or replace function public.escape_game_storage_is_safe_user_path(
  object_name text,
  user_id uuid
)
returns boolean
language sql
stable
security invoker
set search_path = public, storage
as $$
  select
    user_id is not null
    and object_name is not null
    and object_name = trim(both '/' from object_name)
    and object_name not like '%//%'
    and object_name ~ '^[A-Za-z0-9._/-]+$'
    and object_name !~ '(^|/)\.{1,2}($|/)'
    and (storage.foldername(object_name))[1] = 'users'
    and (storage.foldername(object_name))[2] = user_id::text
    and array_length(storage.foldername(object_name), 1) >= 2
    and storage.filename(object_name) <> '';
$$;

comment on function public.escape_game_storage_is_safe_user_path(text, uuid)
is 'Validates Storage paths generated by buildStoragePath(''users'', userId, ...): users/{auth.uid()}/..., safe path segments, and a non-empty filename.';

revoke all on function public.escape_game_storage_is_safe_user_path(text, uuid) from public;
grant execute on function public.escape_game_storage_is_safe_user_path(text, uuid) to authenticated;
grant execute on function public.escape_game_storage_is_safe_user_path(text, uuid) to service_role;

-- Remove previous example-policy names if they were applied manually.
drop policy if exists "Anyone can read public assets" on storage.objects;
drop policy if exists "Authenticated users can upload public assets" on storage.objects;
drop policy if exists "Users can read their own private files" on storage.objects;
drop policy if exists "Users can upload their own private files" on storage.objects;
drop policy if exists "Users can update their own private files" on storage.objects;
drop policy if exists "Users can delete their own private files" on storage.objects;

-- Remove this migration's policy names before recreating them. PostgreSQL does
-- not support CREATE POLICY IF NOT EXISTS.
drop policy if exists "Escape game public assets are readable" on storage.objects;
drop policy if exists "Escape game users can upload own public assets" on storage.objects;
drop policy if exists "Escape game users can update own public assets" on storage.objects;
drop policy if exists "Escape game users can delete own public assets" on storage.objects;
drop policy if exists "Escape game users can read own private files" on storage.objects;
drop policy if exists "Escape game users can upload own private files" on storage.objects;
drop policy if exists "Escape game users can update own private files" on storage.objects;
drop policy if exists "Escape game users can delete own private files" on storage.objects;

create policy "Escape game public assets are readable"
on storage.objects
for select
to anon, authenticated
using (
  bucket_id = public.escape_game_public_assets_bucket_id()
);

comment on policy "Escape game public assets are readable" on storage.objects
is 'Allows anonymous and authenticated reads only from the public assets bucket.';

create policy "Escape game users can upload own public assets"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = public.escape_game_public_assets_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

comment on policy "Escape game users can upload own public assets" on storage.objects
is 'Allows browser uploads to the public bucket only under users/{auth.uid()}/... paths.';

create policy "Escape game users can update own public assets"
on storage.objects
for update
to authenticated
using (
  bucket_id = public.escape_game_public_assets_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
)
with check (
  bucket_id = public.escape_game_public_assets_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

create policy "Escape game users can delete own public assets"
on storage.objects
for delete
to authenticated
using (
  bucket_id = public.escape_game_public_assets_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

create policy "Escape game users can read own private files"
on storage.objects
for select
to authenticated
using (
  bucket_id = public.escape_game_private_data_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

create policy "Escape game users can upload own private files"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = public.escape_game_private_data_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

create policy "Escape game users can update own private files"
on storage.objects
for update
to authenticated
using (
  bucket_id = public.escape_game_private_data_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
)
with check (
  bucket_id = public.escape_game_private_data_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);

create policy "Escape game users can delete own private files"
on storage.objects
for delete
to authenticated
using (
  bucket_id = public.escape_game_private_data_bucket_id()
  and public.escape_game_storage_is_safe_user_path(name, auth.uid())
);
