create table if not exists public.ai_credits (
  user_id text primary key,
  balance integer not null default 20,
  object_images_in_current_batch integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_credit_transactions (
  id bigint generated by default as identity primary key,
  user_id text not null references public.ai_credits(user_id) on delete cascade,
  type text not null,
  amount integer not null,
  reason text not null default '',
  created_at timestamptz not null default now()
);

alter table public.ai_credits enable row level security;
alter table public.ai_credit_transactions enable row level security;

drop policy if exists "Users can read their own ai credits" on public.ai_credits;
create policy "Users can read their own ai credits"
on public.ai_credits
for select
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Users can read their own ai credit transactions" on public.ai_credit_transactions;
create policy "Users can read their own ai credit transactions"
on public.ai_credit_transactions
for select
to authenticated
using (user_id = auth.uid()::text);
