create table if not exists public.shop_pack_sales (
  id bigint generated by default as identity primary key,
  pack_id text not null unique,
  user_id text not null references public.ai_credits(user_id) on delete cascade,
  title text not null default '',
  cost_credits integer not null default 0,
  download_file_name text not null default '',
  status text not null default 'paid',
  purchased_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shop_pack_sales enable row level security;

drop policy if exists "Users can read their own shop pack sales" on public.shop_pack_sales;
create policy "Users can read their own shop pack sales"
on public.shop_pack_sales
for select
to authenticated
using (user_id = auth.uid()::text);

create or replace function public.purchase_shop_pack(
  p_pack_id text,
  p_user_id text,
  p_title text,
  p_cost_credits integer,
  p_download_file_name text
)
returns table (
  balance integer,
  purchased_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_balance integer;
  paid_at timestamptz := now();
begin
  if p_pack_id is null or length(trim(p_pack_id)) = 0 then
    raise exception 'Pack manquant.' using errcode = '22023';
  end if;

  if p_user_id is null or length(trim(p_user_id)) = 0 or p_user_id = 'anonymous' then
    raise exception 'Utilisateur manquant.' using errcode = '22023';
  end if;

  if p_cost_credits is null or p_cost_credits <= 0 then
    raise exception 'Cout en credits invalide.' using errcode = '22023';
  end if;

  insert into public.ai_credits (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select ai_credits.balance
  into current_balance
  from public.ai_credits
  where ai_credits.user_id = p_user_id
  for update;

  if current_balance < p_cost_credits then
    raise exception 'Credits IA insuffisants (%/%).', current_balance, p_cost_credits using errcode = 'P0001';
  end if;

  insert into public.shop_pack_sales (
    pack_id,
    user_id,
    title,
    cost_credits,
    download_file_name,
    status,
    purchased_at,
    created_at,
    updated_at
  )
  values (
    p_pack_id,
    p_user_id,
    coalesce(p_title, ''),
    p_cost_credits,
    coalesce(p_download_file_name, ''),
    'paid',
    paid_at,
    paid_at,
    paid_at
  );

  update public.ai_credits
  set
    balance = current_balance - p_cost_credits,
    updated_at = paid_at
  where user_id = p_user_id;

  insert into public.ai_credit_transactions (
    user_id,
    type,
    amount,
    reason,
    created_at
  )
  values (
    p_user_id,
    'spend',
    -p_cost_credits,
    'shop_pack:' || p_pack_id || ':' || coalesce(p_title, ''),
    paid_at
  );

  return query select current_balance - p_cost_credits, paid_at;
end;
$$;

revoke execute on function public.purchase_shop_pack(text, text, text, integer, text) from public;
revoke execute on function public.purchase_shop_pack(text, text, text, integer, text) from anon;
revoke execute on function public.purchase_shop_pack(text, text, text, integer, text) from authenticated;
grant execute on function public.purchase_shop_pack(text, text, text, integer, text) to service_role;
