import PreviewTab from './PreviewTab';

export default function PreviewPlayerPanel({
  editor,
  preview,
  heroCharacterPreviewRequestKey = 0,
  sharedPlayerMode = false,
}) {
  return (
    <PreviewTab
      playScene={preview.playScene}
      viewerImage={preview.viewerImage}
      setViewerImage={preview.setViewerImage}
      playingCinematic={preview.playingCinematic}
      playingSlideIndex={preview.playingSlideIndex}
      currentSlide={preview.currentSlide}
      setPlayingCinematic={preview.setPlayingCinematic}
      setPlayingSlideIndex={preview.setPlayingSlideIndex}
      closeCinematic={preview.closeCinematic}
      advanceCinematic={preview.advanceCinematic}
      audioRef={preview.audioRef}
      onSceneTimerEnd={preview.applySceneTimerEnd}
      triggerHotspot={preview.triggerHotspot}
      resetPreview={preview.resetPreview}
      saveGameState={preview.saveGameState}
      loadGameState={preview.loadGameState}
      restoreLastChoiceSnapshot={preview.restoreLastChoiceSnapshot}
      getSceneLabel={editor.getSceneLabel}
      dialogue={preview.dialogue}
      inventory={preview.inventory}
      storyVariables={preview.storyVariables}
      adventureJournalEntries={preview.adventureJournalEntries}
      chosenConversationReplyIds={preview.chosenConversationReplyIds}
      hiddenConversationReplyIds={preview.hiddenConversationReplyIds}
      completedHotspotIds={preview.completedHotspotIds}
      addInventoryItem={preview.addInventoryItem}
      removeInventoryItem={preview.removeInventoryItem}
      playerLives={preview.playerLives}
      heroAdventure={preview.heroAdventure}
      heroState={preview.heroState}
      heroSetupComplete={preview.heroSetupComplete}
      equippedHeroItemIds={preview.equippedHeroItemIds}
      equippedHeroSlotMap={preview.equippedHeroSlotMap}
      lastChoiceSnapshot={preview.lastChoiceSnapshot}
      adjustHeroStat={preview.adjustHeroStat}
      lastDiceRoll={preview.lastDiceRoll}
      rollHeroDie={preview.rollHeroDie}
      rollHeroSetupSkills={preview.rollHeroSetupSkills}
      completeHeroSetup={preview.completeHeroSetup}
      sceneTimerResetKey={preview.sceneTimerResetKey}
      setInventory={preview.setInventory}
      setSelectedInventoryIds={preview.setSelectedInventoryIds}
      usedSceneObjectIds={preview.usedSceneObjectIds}
      revealedSceneObjectIds={preview.revealedSceneObjectIds}
      sceneObjectTextOverrides={preview.sceneObjectTextOverrides}
      markSceneObjectUsed={preview.markSceneObjectUsed}
      markHotspotCompleted={preview.markHotspotCompleted}
      project={editor.project}
      selectedInventoryIds={preview.selectedInventoryIds}
      openInventoryItem={preview.openInventoryItem}
      equipHeroItem={preview.equipHeroItem}
      unequipHeroItem={preview.unequipHeroItem}
      setDraggedInventoryId={preview.setDraggedInventoryId}
      draggedInventoryId={preview.draggedInventoryId}
      combineInventoryItems={preview.combineInventoryItems}
      setDialogue={preview.setDialogue}
      activeEnigma={preview.activeEnigma}
      activeConversation={preview.activeConversation}
      activeEnding={preview.activeEnding}
      choiceEffectNotices={preview.choiceEffectNotices}
      closeConversation={preview.closeConversation}
      closeEnding={preview.closeEnding}
      clearChoiceEffectNotices={preview.clearChoiceEffectNotices}
      isConversationReplyAvailable={preview.isConversationReplyAvailable}
      getConversationReplyLockReason={preview.getConversationReplyLockReason}
      chooseConversationReply={preview.chooseConversationReply}
      heroCharacterPreviewRequestKey={heroCharacterPreviewRequestKey}
      enigmaCodeInput={preview.enigmaCodeInput}
      setEnigmaCodeInput={preview.setEnigmaCodeInput}
      enigmaColorAttempt={preview.enigmaColorAttempt}
      setEnigmaColorAttempt={preview.setEnigmaColorAttempt}
      pushEnigmaColor={preview.pushEnigmaColor}
      closeEnigma={preview.closeEnigma}
      submitEnigma={preview.submitEnigma}
      enigmaPuzzleOrder={preview.enigmaPuzzleOrder}
      enigmaPuzzleSelectedIndex={preview.enigmaPuzzleSelectedIndex}
      clickPuzzlePiece={preview.clickPuzzlePiece}
      enigmaDragBank={preview.enigmaDragBank}
      enigmaDragSlots={preview.enigmaDragSlots}
      enigmaDraggedPiece={preview.enigmaDraggedPiece}
      setEnigmaDraggedPiece={preview.setEnigmaDraggedPiece}
      moveDragPieceToSlot={preview.moveDragPieceToSlot}
      returnDragPieceToBank={preview.returnDragPieceToBank}
      enigmaRotationAngles={preview.enigmaRotationAngles}
      rotatePuzzlePiece={preview.rotatePuzzlePiece}
      simonPlaybackIndex={preview.simonPlaybackIndex}
      simonPlayerTurn={preview.simonPlayerTurn}
      startSimonPlayback={preview.startSimonPlayback}
      sharedPlayerMode={sharedPlayerMode}
    />
  );
}
