export const NARRATIVE_TEMPLATE_CONFIGS = {
  narrative_investigation: {
    actName: 'Dossier I',
    scenes: ['Bureau dé la detective', 'Appartement du temoin', 'Quai de nuit'],
    intros: ['Une disparition, trois versions, et un dossier qui refuse de se fermer.', 'Le temoin cache une partie de la verite.', 'Le quai attend ta conclusion.'],
    npc: 'Temoin',
    opening: 'Je peux parler, mais je ne veux pas être accuse. Que veux-tu savoir ?',
    itemName: 'Photo froissee',
    itemIcon: '[]',
    supportItemName: 'Releve d appels',
    supportItemIcon: 'TEL',
    finalItemName: 'Aveu signe',
    finalItemIcon: 'SIG',
    variableKey: 'confiance_temoin',
    enigmaName: 'Contradiction du dossier',
    enigmaQuestion: 'Quelle preuve contredit l alibi ?',
    choices: ['La photo froissee', 'La montre cassee', 'Le ticket de train'],
    solution: 'La photo froissee',
    goodTitle: 'Affaire résolue',
    badTitle: 'Fausse piste',
    secretTitle: 'Le temoin protegeait quelqu un',
  },
  magic_forest: {
    actName: 'Clairiere I',
    scenes: ['Lisiere enchantee', 'Arbre oracle', 'Source des lucioles'],
    intros: ['La forêt change de chemin quand on ment.', 'L arbre oracle ecoute les intentions.', 'La source revele une sortie differente selon les promesses faites.'],
    npc: 'Oracle',
    opening: 'Chaque sentier à un prix. Quelle verite apportes-tu ?',
    itemName: 'Graine d argent',
    itemIcon: '*',
    supportItemName: 'Ecorce gravee',
    supportItemIcon: '[]',
    finalItemName: 'Rosace des lucioles',
    finalItemIcon: 'O',
    variableKey: 'respect_foret',
    enigmaName: 'Serment des racines',
    enigmaQuestion: 'Quel mot ouvre le passage des lucioles ?',
    choices: ['Merci', 'Pouvoir', 'Silence'],
    solution: 'Merci',
    goodTitle: 'La forêt te laisse passer',
    badTitle: 'Les ronces se referment',
    secretTitle: 'La clairiere cachée',
  },
  survival_choices: {
    actName: 'Jour 1',
    scenes: ['Epave sur la plage', 'Forêt humide', 'Falaise du signal'],
    intros: ['Tu te reveilles pres d’une epave. L eau monte.', 'La forêt donne de quoi survivre, mais chaque detour coute du temps.', 'Depuis la falaise, un signal peut sauver quelqu un ou te trahir.'],
    npc: 'Survivante',
    opening: 'On ne tiendra pas longtemps. On cherche de l eau, un abri ou un signal ?',
    itemName: 'Gourde intacte',
    itemIcon: '[]',
    supportItemName: 'Carte detrempee',
    supportItemIcon: 'MAP',
    finalItemName: 'Fumigene de signal',
    finalItemIcon: 'SOS',
    variableKey: 'energie',
    enigmaName: 'Signal de detresse',
    enigmaQuestion: 'Quel signal international demande de l aide ?',
    choices: ['SOS', 'NORD', 'FEU'],
    solution: 'SOS',
    goodTitle: 'Sauvetage à l’aube',
    badTitle: 'Nuit sans abri',
    secretTitle: 'Le refuge de la falaise',
  },
  npc_dialogue: {
    actName: 'Rencontre I',
    scenes: ['Taverne calme', 'Arriere-salle', 'Porte de la cite'],
    intros: ['Tout commence par une conversation.', 'L arriere-salle garde les secrets du PNJ.', 'La porte juge ce que tu as appris.'],
    npc: 'Archiviste',
    opening: 'Je sais ou est la clé, mais je ne parlé pas aux inconnus presses.',
    itemName: 'Sceau dé confiance',
    itemIcon: '[]',
    supportItemName: 'Phrase de passe',
    supportItemIcon: 'PWD',
    finalItemName: 'Cle de la cite',
    finalItemIcon: 'KEY',
    variableKey: 'confiance_archiviste',
    enigmaName: 'Question de memoire',
    enigmaQuestion: 'Quel detail l archiviste a-t-il mentionne ?',
    choices: ['La clé', 'La pluie', 'La cloche'],
    solution: 'La clé',
    goodTitle: 'Alliance conclue',
    badTitle: 'Conversation rompue',
    secretTitle: 'Confidence de l archiviste',
  },
  negotiation: {
    actName: 'Table I',
    scenes: ['Salle du conseil', 'Couloir des apartes', 'Balcon du pacte'],
    intros: ['Deux camps attendent une decision.', 'Les vrais accords se font loin des regards.', 'Le pacte final depend de ta credibilite.'],
    npc: 'Ambassadrice',
    opening: 'Tu veux un accord ? Alors dis-moi qui doit ceder en premier.',
    itemName: 'Lettre de garantie',
    itemIcon: '[]',
    supportItemName: 'Clause annotee',
    supportItemIcon: 'ART',
    finalItemName: 'Pacte scelle',
    finalItemIcon: 'SIG',
    variableKey: 'credit_diplomatique',
    enigmaName: 'Clause cachée',
    enigmaQuestion: 'Quelle clause évite la trahison ?',
    choices: ['Temoin neutre', 'Promesse orale', 'Retard volontaire'],
    solution: 'Temoin neutre',
    goodTitle: 'Traite signe',
    badTitle: 'Rupture des pourparlers',
    secretTitle: 'Alliance discrete',
  },
  narrative_maze: {
    actName: 'Boucle I',
    scenes: ['Entree du labyrinthe', 'Salle dés echos', 'Centre mouvant'],
    intros: ['Le labyrinthe ne se traverse pas: il se raconte dans le bon ordre.', 'Les echos repetent tes anciens choix.', 'Le centre attend’une version coherente de ton histoire.'],
    npc: 'Echo',
    opening: 'Tu es déjà venu ici, même si tu ne t en souviens pas. Quelle trace suis-tu ?',
    itemName: 'Fil rouge',
    itemIcon: '~',
    supportItemName: 'Fragment d echo',
    supportItemIcon: 'ECO',
    finalItemName: 'Cle du centre',
    finalItemIcon: 'KEY',
    variableKey: 'memoire_labyrinthe',
    enigmaName: 'Ordre des echos',
    enigmaQuestion: 'Quel mot revient a chaque boucle ?',
    choices: ['Retour', 'Victoire', 'Oubli'],
    solution: 'Retour',
    goodTitle: 'Sortie trouvee',
    badTitle: 'Boucle infinie',
    secretTitle: 'Centre revele',
  },
};
